### ISSUE TITLE
Change type for passengerIds in CommonOfferPartAttributes from string to array

### ISSUE THREAD

**Issue by micaelvesterlund** [UnionInternationalCheminsdeFer/OSDM#248]
In **OSDM-online-api-v1.4.0-rc.yml** should the property _passengerIds_ in the object _CommonOfferPartAttributes_ change type from string to array.

from:
```
passengerIds:
          type: string
          description: Id of the passenger
```
to:
```
passengerIds:
          type: array
          items:
            description: Id of the passenger
            type: string
```
