### ISSUE TITLE
externalRef in patch booking

### ISSUE THREAD

**Issue by Linus-Turnit** [UnionInternationalCheminsdeFer/OSDM#663]
Keep the possibility to patch externalRef to a booking.
We have customers using this to add their own shopping-basket id after payment on their side.

**Comment by Azurab** [comment]
IMO, standardized HTTP header traceparent and tracestate attributes with no impact on business domain payloads should solve this case.
Hint: https://www.w3.org/TR/trace-context/#header-name-0:~:text=Following%20is%20the,considered%20a%20default.

**Comment by Linus-Turnit** [comment]
Actually in this case externalRef is a vital part of the booking-payload and must be persisted in the booking. 
The customer has a temporary shopping-basked until external payment is finished. The real code for the distributors, is available after payment and they want to update the allocator/provider booking.externalRef with the new code for traceability and search possibilities

**Comment by jspetrak** [comment]
Removed from `BookingPatchRequest` in 3.1, put it back.

```
externalRef:
          type: string
          description: The unique booking reference in the distributor/reseller system. Usually refers to an order number or PNR.
          nullable: true
```
